@startuml

hide members

package "main" {
    class MainCDI
    class MainJPASchemaGen
}
package "test" {
    class ItemServiceTest
}

package "service" {
    interface NumberGenerator
    class IsbnGenerator << @ThirteenDigits >>
    class IssnGenerator << @EightDigits >>
    class MockGenerator << @Alternative >>
    class ItemService

    ItemService <.right. NumberGenerator : @Inject
    NumberGenerator <|.. IsbnGenerator
    NumberGenerator <|.. IssnGenerator
    NumberGenerator <|.. MockGenerator
}

package "model" {
    class Chapter << @Entity >> #8FBC8F
    class Book << @Entity >>
    class String
    enum Language
    class LanguageConverter << @Converter >>

    Book --> "*" String
    Book -right-> "*" Chapter
    Book --> Language
    Book ..> LanguageConverter
}

package "util" {
    annotation Loggable
    class LoggingInterceptor << @Loggable >>
    class LoggingProducer
    class CDIDebug << Extension >>
}

main ..> service
test ..> service
service ..> model
service ..> util

@enduml