@startuml

hide members

package "test" {
    class ItemServiceTest
}

package "webapp"  <<Cloud>> {
    class newItem  #8FBC8F
    class newBook  #8FBC8F
    class newCD  #8FBC8F
    class template  #8FBC8F
}

package "view"  {
    class ItemController  #8FBC8F
}

package "service" {
    interface NumberGenerator
    class IsbnGenerator << @ThirteenDigits >>
    class IssnGenerator << @EightDigits >>
    class MockGenerator << @Alternative >>
    class ItemService << @Stateless >>
    class DatabaseProducer
    class DBPopulator << @Singleton >>

    ItemService <.. NumberGenerator : @Inject
    DBPopulator <.. ItemService : @Inject
    NumberGenerator <|.. IsbnGenerator
    NumberGenerator <|.. IssnGenerator
    NumberGenerator <|.. MockGenerator
}

package "model" {
    class DebugListener
    class Item << @Entity >> << @NamedQuery >>
    class CD << @Entity >> << @NamedQuery >> << @EntityListeners >>
    class Track << @Entity >>
    class Chapter << @Entity >>
    class Book << @Entity >> << @NamedQuery >> << @EntityListeners >> << ChronologicalDates >>
    class String
    enum Language
    class LanguageConverter << @Converter >>

    Item <|-- CD
    Item <|-- Book
    CD --> "*" Track
    Book --> "*" String
    Book --> "*" Chapter
    Book --> Language
    Book ..> LanguageConverter
}

package "constraints" {
    annotation MusicGenre << @Constraint >>
    annotation ChronologicalDates << @Constraint >>
    class ChronologicalDatesValidator
}

package "util" {
    annotation Loggable
    class LoggingInterceptor << @Loggable >>
    class LoggingProducer
    class CDIDebug << Extension >>
}

test ..> service
webapp ..> view
view ..> service
service ..> model
service ..> util
model ..> constraints

@enduml