@startuml

hide members

package "main" {
    class MainREST #8FBC8F
}

package "webapp"  <<Cloud>> {
    class newItem
    class newBook
    class newCD
    class template
}

package "view"  {
    class ItemController
}

package "service" {
    interface NumberGenerator
    class IsbnGenerator << @ThirteenDigits >>
    class IssnGenerator << @EightDigits >>
    class MockGenerator << @Alternative >>
    class ItemService << @Stateless >> << Path >>
    class ApplicationConfig
    class DatabaseProducer
    class DBPopulator << @Singleton >>

    ItemService <.right. NumberGenerator : @Inject
    DBPopulator <.down. ItemService : @Inject
    NumberGenerator <|.. IsbnGenerator
    NumberGenerator <|.. IssnGenerator
    NumberGenerator <|.. MockGenerator
}

package "model" {
    class DebugListener
    class Item << @Entity >> << @NamedQuery >>
    class CD << @Entity >> << @NamedQuery >> << @EntityListeners >> << XmlRootElement >>
    class Track << @Entity >>
    class Chapter << @Entity >>
    class Book << @Entity >> << @NamedQuery >> << @EntityListeners >> << ChronologicalDates >> << XmlRootElement >>
    class String
    enum Language
    class LanguageConverter << @Converter >>

    Item <|-- CD
    Item <|-- Book
    CD --> "*" Track
    Book --> "*" String
    Book -right-> "*" Chapter
    Book --> Language
    Book ..> LanguageConverter
}

package "constraints" {
    annotation MusicGenre << @Constraint >>
    annotation ChronologicalDates << @Constraint >>
    class ChronologicalDatesValidator
}

package "util" {
    annotation Loggable
    class LoggingInterceptor << @Loggable >>
    class LoggingProducer
    class CDIDebug << Extension >>
}

webapp ..> view
view ..> service
service ..> model
service ..> util
model ..> constraints

@enduml